### ISSUE TITLE
Als je 'twijfel' kiest mag je niet meer 'wel' of 'nee' kiezen

### ISSUE THREAD

**Issue by SimonDamminga** [davinci-ao/examentool#1]
**Welke Feature**
- Als examinator wil ik een criterium als zijnde (niet) waargenomen kunnen markeren
- Als examinator wil ik een criterium als zijnde twijfelgeval kunnen markeren

**Waargenomen gedrag**
Als ik op 'twijfelgeval' klik dan wordt 'wel' of 'nee' niet ongedaan gemaakt

**Verwacht gedrag**
Als je tijdens de afname van een examen kiest voor twijfel en je hebt al gekozen voor 'ja' of 'nee' moet deze gedeactiveerd worden

**Bug Namaken**
1. Start een examen
2. Klik bij een vraag op 'ja' of 'nee'
3. Klik op twijfel

**Verzie & Waarmee getest**

- OS: Windows 10
- Browser: Chrome v. 70
- Applicatie verzie: 0.1

**Comment by richard-boon** [comment]
Dit is geen bug. Dit is normaal gedrag.
