### ISSUE TITLE
Als je op "add exam" drukt wordt er geen menu geopend dat je kan sluiten.

### ISSUE THREAD

**Issue by JWOverschot** [davinci-ao/examentool#2]
#### Welke Feature
- ls beheerder wil ik een examen kunnen toevoegen  

#### Waargenomen gedrag
Er komt geen menu tevoorschijn als je op "add exam" klikt  

#### Verwacht gedrag
Als je op "add exam" klikt dan komt er een menu tevoorschijn die je kan sluiten met een kruisje links boven in.  

#### Bug reproduceren
1.  Klik in het menu op “Add exam”.  

#### Verzie & Waarmee getest
- OS: Windows 10
- Browser: Chrome v. 70
- Applicatie verzie: 0.1

**Comment by richard-boon** [comment]
Dit is geen bug. Testcase is verouderd. Als bijlagen een nieuwe testcase die up-to-date is.
[Testcase Als beheerder wil ik een examen kunnen toevoegen.docx](https://github.com/davinci-ao/examentool/files/2566106/Testcase.Als.beheerder.wil.ik.een.examen.kunnen.toevoegen.docx)
